import Head from 'next/head';
import Header from '../Components/Header';
import HeroSection from '../Components/HeroSection';
import Nav from '../Components/Navbar';

export default function Home() {
  return (
    <div className="font-poppins">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <div className="lg:w-[80%] mx-auto">
        <HeroSection />
      </div>
    </div>
  );
}
